---
abstract: 'yet another switch statement for Perl'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.012, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlX-Switch
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  PerlX::Switch:
    file: lib/PerlX/Switch.pm
    version: 0.003
requires:
  Devel::Caller: 0
  Devel::LexAlias: 0.05
  Exporter: 5.57
  PadWalker: 0
  Parse::Keyword: 0.06
  match::simple: 0.004
  perl: 5.014
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/PerlX-Switch/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=PerlX-Switch
  homepage: https://metacpan.org/release/PerlX-Switch
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-perlx-switch
version: 0.003
